### ISSUE TITLE
Remove extraneous items from config

### ISSUE THREAD

**Issue by gjost** [denshoproject/ddr-local#279] opened 2020-05-15 16:57 UTC
The DDR config files are a gnarly mess.  Most of the items could just be left out of `ddrlocal.cfg` and set in `DDR.config.py`.  Find out which items are most/least useful to staff and remove everything else.

**Comment by GeoffFroh** [comment] 2020-06-23 21:20
Duplicate of #281

**Closed by GeoffFroh** 2020-06-23 21:20 UTC
Labels: enhancement
